# Generated by Django 4.2.19 on 2025-02-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0003_shopuser_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={'verbose_name': 'shopuser', 'verbose_name_plural': 'shopusers'},
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='shopuser_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='shopuser_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
