# Generated by Django 4.2.19 on 2025-02-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shopuser_options_alter_shopuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='last_name',
        ),
    ]
