# Generated by Django 4.2.19 on 2025-02-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_products_alter_orderproducts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_products', to='shop.product'),
        ),
    ]
