version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: coffe-shop-pg
    environment:
      POSTGRES_USER: postgres        # Имя пользователя
      POSTGRES_PASSWORD: coffeshop   # Пароль
      POSTGRES_DB: coffe_shop        # Имя базы данных
    ports:
      - "5432:5432"               # Пробрасываем порт
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Монтируем данные для их сохранения

volumes:
  postgres_data:
