# Generated by Django 4.2.19 on 2025-05-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='customer',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='customer_id',
            field=models.CharField(default='anonymous', max_length=255, unique=True),
        ),
    ]
