# Generated by Django 4.2.21 on 2025-07-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0002_remove_chatsession_agent_remove_chatsession_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-created_at']},
        ),
    ]
